org: dodo
org-billingmanager:
  ldap_users: []
  users: []
  ldap_group: ""
  ldap_groups: []
org-manager:
  ldap_users: []
  users:
  - admin
  - abby
  ldap_group: ""
  ldap_groups: []
org-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
  ldap_groups: []
private-domains: []
enable-remove-private-domains: true
enable-org-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 1000
total-services: -1
paid-service-plans-allowed: false
enable-remove-users: true
total_private_domains: 0
total_reserved_route_ports: 0
total_service_keys: 0
app_instance_limit: 0
